[package]
name = "lisp"
version = "0.1.0"
authors = ["Micheal Baumfalk <me@baumfalk.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.1.2"